#!/bin/sh

# Config Files
alias confvk="nvim ~/.config/VSCodium/User/keybindings.json"
alias confvs="nvim ~/.config/VSCodium/User/settings.json"
alias confvu="cd ~/.config/VSCodium/User"
alias confv="cd ~/.config/VSCodium"

alias confa="nvim ~/.config/alacritty/alacritty.yml"

alias confzf="nvim ~/.config/zsh/zsh-functions"
alias confzv="nvim ~/.config/zsh/zsh-vim-mode"
alias confza="nvim ~/.config/zsh/zsh-aliases"
alias confze="nvim ~/.config/zsh/zsh-exports"
alias confzp="nvim ~/.config/zsh/zsh-prompt"
alias confz="nvim ~/.config/zsh/.zshrc"

alias confnl="cd ~/.config/nvim/lua/emrhnpla/"
alias confn="nvim ~/.config/nvim/init.lua"

alias conft="nvim ~/.config/tmux/tmux.conf"

alias dotfiles="cd ~/.dotfiles"

alias config="cd ~/.config"


# Folders
alias repos="cd ~/All/Programming/Repos"


# Package Manager & Aur Helper
alias Ro="pacman -Qtdq | doas pacman -Rns -"
alias Rns="doas pacman -Rns"
alias Ss="doas pacman -Ss"
alias Sy="doas pacman -Sy"
alias Rs="doas pacman -Rs"
alias S="doas pacman -S"
alias R="doas pacman -R"
alias Qo="pacman -Qtdq"
alias Syu="doas paru"
alias Sua="paru -Sua"
alias Pss="paru -Ss"
alias Ps="paru -S"
alias P="paru"


# Git
alias Gl-o="git log --oneline"
alias Gsl="git stash list"
alias Gsa="git stash save"
alias Gss="git stash show"
alias Gsd="git stash drop"
alias Gsp="git stash pop"
alias Gch="git checkout"
alias Gsw="git switch"
alias Gr="git restore"
alias Grm="git remote"
alias Grb="git rebase"
alias Grs="git reset"
alias Gcl="git clone"
alias Gs="git status"
alias Gc="git commit"
alias Gb="git branch"
alias Gm="git merge"
alias Gf="git fetch"
alias Gpl="git pull"
alias Gp="git push"
alias Gd="git diff"
alias Gi="git init"
alias Ga="git add"
alias Gl="git log"
alias G="git"


# Cargo
alias cgp="cargo publish"
alias cgu="cargo update"
alias cgb="cargo build"
alias cgc="cargo check"
alias cgi="cargo init"
alias cgt="cargo test"
alias cgr="cargo run"
alias cgn="cargo new"
alias cga="cargo add"
alias cg="cargo"


# Apps
alias trash-empty="sudo trash-empty"
alias scrcpy="devour scrcpy"
alias d="devour dolphin"
alias code="vscodium"
alias nv="nvim"
alias v="nvim"


# Other
alias zsh-update-plugins="find "$ZDOTDIR/plugins" -type d -exec test -e '{}/.git' ';' -print0 | xargs -I {} -0 git -C {} pull -q"
alias mirrord="sudo reflector --latest 50 --number 20 --sort delay --save /etc/pacman.d/mirrorlist"
alias mirrors="sudo reflector --latest 50 --number 20 --sort score --save /etc/pacman.d/mirrorlist"
alias mirrora="sudo reflector --latest 50 --number 20 --sort age --save /etc/pacman.d/mirrorlist"
alias mirror="sudo reflector -f 30 -l 30 --number 10 --verbose --save /etc/pacman.d/mirrorlist"
alias fgrep="fgrep --color=auto"
alias egrep="egrep --color=auto"
alias grep="grep --color=auto"
alias ll="ls -la --color"
alias ls="ls --color"
alias ka="killall"
alias pls="doas"
alias cat="bat"
alias c="clear"
alias q="exit"
alias t="tmux"
