#!/bin/sh

# Config Files
alias confa="nvim ~/.config/alacritty/alacritty.yml"
alias confnm="nvim ~/.config/nvim/mappings.vim"
alias confns="nvim ~/.config/nvim/settings.vim"
alias confzf="nvim ~/.config/zsh/zsh-functions"
alias confzv="nvim ~/.config/zsh/zsh-vim-mode"
alias confnp="nvim ~/.config/nvim/plugins.vim"
alias confnl="cd ~/.config/nvim/lua/emrhnpla"
alias confza="nvim ~/.config/zsh/zsh-aliases"
alias confze="nvim ~/.config/zsh/zsh-exports"
alias confzp="nvim ~/.config/zsh/zsh-prompt"
alias confn="nvim ~/.config/nvim/init.vim"
alias confz="nvim ~/.config/zsh/.zshrc"
alias dotfiles="cd ~/.dotfiles"


# Package Manager & Aur Helper
alias Ro="pacman -Qtdq | doas pacman -Rns -"
alias Ss="doas pacman -Ss"
alias Sy="doas pacman -Sy"
alias Rs="doas pacman -Rs"
alias S="doas pacman -S"
alias R="doas pacman -R"
alias Qo="pacman -Qtdq"
alias Syu="doas paru"
alias Sua="paru -Sua"
alias Pss="paru -Ss"
alias Ps="paru -S"
alias P="paru"


# Git
alias Gp-uom="git push -u origin main"
alias Gl-o="git log --oneline"
alias Gch="git checkout"
alias Gsw="git switch"
alias Gr="git restore"
alias Grm="git remote"
alias Grs="git reset"
alias Gcl="git clone"
alias Gs="git status"
alias Gc="git commit"
alias Gb="git branch"
alias Gm="git merge"
alias Gf="git fetch"
alias Gpl="git pull"
alias Gp="git push"
alias Gd="git diff"
alias Gi="git init"
alias Ga="git add"
alias Gl="git log"
alias G="git"


# DotNet
alias Dusi="dotnet user-secrets init"
alias Dwr="dotnet watch run"
alias Drs="dotnet restore"
alias Drm="dotnet remove"
alias Dp="dotnet publish"
alias Db="dotnet build"
alias Dc="dotnet clean"
alias Dsln="dotnet sln"
alias Dl="dotnet list"
alias Dt="dotnet test"
alias Dr="dotnet run"
alias Da="dotnet add"
alias Dn="dotnet new"
alias D="dotnet"

# EntityFramework Core
alias Defma="function _(){ dotnet ef migrations add $1 -p $2 -s $3 }; _"
alias Defda="function _(){ dotnet ef database update -p $1 -s $2 }; _"


# Docker
alias DKcl="doas docker container logs"
alias DKit="doas docker images tag"
alias DKi="doas docker inspect"
alias DKstr="doas docker start"
alias DKa="doas docker attach"
alias DKstp="doas docker stop"
alias DKi="doas docker images"
alias DKp="doas docker pull"
alias DKps="doas docker ps"
alias DKrm="doas docker rm"
alias DKr="doas docker run"
alias docker="doas docker"
alias DK="doas docker"


# PostgreSQL
alias psqlinit="postgres initdb -D /var/lib/postgres/data"
alias psqluser="sudo -u postgres -i"


# NodeJS
alias Nrs="npm run serve"
alias Nrb="npm run build"
alias Ni="npm install"
alias Ninit="npm init"


# Apps
alias vw="nvim ~/All/vimwiki/index.wiki"
alias prime-run="devour prime-run"
alias scrcpy="devour scrcpy"
alias d="devour dolphin"
alias stm="steam-tui"
alias code="vscodium"
alias nv="nvim"
alias v="nvim"


# Other
alias zsh-update-plugins="find "$ZDOTDIR/plugins" -type d -exec test -e '{}/.git' ';' -print0 | xargs -I {} -0 git -C {} pull -q"
alias mirrord="sudo reflector --latest 50 --number 20 --sort delay --save /etc/pacman.d/mirrorlist"
alias mirrors="sudo reflector --latest 50 --number 20 --sort score --save /etc/pacman.d/mirrorlist"
alias mirrora="sudo reflector --latest 50 --number 20 --sort age --save /etc/pacman.d/mirrorlist"
alias mirror="sudo reflector -f 30 -l 30 --number 10 --verbose --save /etc/pacman.d/mirrorlist"
alias fgrep="fgrep --color=auto"
alias egrep="egrep --color=auto"
alias grep="grep --color=auto"
alias ll="ls -la --color"
alias ls="ls --color"
alias ka="killall"
alias pls="doas"
alias cat="bat"
alias c="clear"
alias q="exit"
